version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - bruno-campos
    default_assignees:
      - bruno-campos
    default_labels:
      - "dependencies"
      - "dependabot"
